Repository openfun/jitsi-magnify, pull requests merged in 2022-09, with the labels that each got.

#96 Fix csrf error on admin page
  sandbox/settings.py
Labels: bug

#98 ⬆️(backend) upgrade drf-yasg to version 1.21.4
  setup.cfg
Labels: bug, dependencies

#101 ✨(backend) enable cors headers
  CHANGELOG.md
  sandbox/settings.py
  setup.cfg
Labels: feature
