Repository openfun/jitsi-magnify, pull requests merged in 2023-01, with the labels that each got.

#149 ✨(users) add timezone field to user API
  src/magnify/apps/core/serializers/users.py
  tests/apps/core/test_core_api_meetings.py
  tests/apps/core/test_core_api_rooms.py
  tests/apps/core/test_core_api_users.py
Labels: improvement

#141 👷(circleci) publish docker image
  .circleci/config.yml
Labels: feature

#156 🔧(magnify-site) disable treeshaking for production build
  src/frontend/magnify/apps/magnify-site/vite.config.ts
Labels: bug

#155 ♻️(user) make "email" field optional on User
  sandbox/settings.py
  src/magnify/apps/core/authentication.py
  src/magnify/apps/core/factories.py
  src/magnify/apps/core/migrations/0001_initial.py
  src/magnify/apps/core/models.py
  tests/apps/core/test_core_authentication.py
Labels: improvement

#159 👷(project) rename docker-compose production stack to demo
  .gitignore
  Makefile
  README.md
  docker-compose.yml
  docker/files/etc/nginx/conf.d/default.conf
  docs/env.md
  env.d/common
  env.d/crowdin.dist
  env.d/demo
  env.d/kc_postgresql
  env.d/mysql
  env.d/postgresql
Labels: improvement

#162 ✨(users) allow differentiating device users from human users
  docs/env.md
  sandbox/settings.py
  src/magnify/apps/core/authentication.py
  src/magnify/apps/core/migrations/0001_initial.py
  src/magnify/apps/core/models.py
  src/magnify/apps/core/serializers/users.py
  tests/apps/core/test_core_api_meetings.py
  tests/apps/core/test_core_api_rooms.py
  tests/apps/core/test_core_api_users.py
  tests/apps/core/test_core_authentication_delegated_jwt_authentication.py
Labels: feature

#163 ✨(users) allow deactivating the creation of users via the API
  docs/env.md
  sandbox/settings.py
  src/magnify/apps/core/permissions.py
  tests/apps/core/test_core_api_users.py
Labels: feature
