Repository openfun/jitsi-magnify, pull requests merged in 2023-06, with the labels that each got.

#199 ✨(jitsi) allow adding a prefix to the Jitsi room names
  docs/env.md
  sandbox/settings.py
  src/magnify/apps/core/models.py
  tests/apps/core/test_core_models_meetings.py
  tests/apps/core/test_core_models_rooms.py
Labels: feature

#203 📝(frontend) update README.md
  README.md
Labels: documentation

#214 ✨(frontend) map colors grommet with cunningham
  CHANGELOG.md
  README.md
  src/frontend/packages/core/cunningham.ts
  src/frontend/packages/core/package.json
  src/frontend/packages/core/src/components/app/MagnifyProvider/index.tsx
  src/frontend/packages/core/src/components/app/MagnifyTestingProvider/index.tsx
  src/frontend/packages/core/src/components/design-system/Toggle/Toggle.test.tsx
  src/frontend/packages/core/src/components/profile/DeleteAccountBlock/DeleteAccountBlock.test.tsx
  src/frontend/packages/core/src/components/rooms/RoomRow/RoomRow.tsx
  src/frontend/packages/core/src/components/users/avatar/UserAvatar.tsx
  src/frontend/packages/core/src/components/users/row/UserRow.test.tsx
  src/frontend/packages/core/src/components/users/search-modal/UserSearchModal.test.tsx
  src/frontend/packages/core/src/cunningham-tokens.ts
  src/frontend/packages/core/src/themes/theme.ts
  src/frontend/packages/core/src/utils/helpers/merge.ts
  src/frontend/sandbox/cunningham.ts
  src/frontend/sandbox/package.json
  src/frontend/sandbox/src/cunningham-tokens.css
  src/frontend/sandbox/src/cunningham-tokens.ts
  src/frontend/sandbox/src/index.css
  src/frontend/sandbox/src/main.tsx
  src/frontend/yarn.lock
Labels: feature

#217 🚸(frontend) move room public switch to the security section
  src/frontend/packages/core/src/components/rooms/RoomConfig/RoomConfig.tsx
Labels: improvement

#224 🐛️(frontend) fix SimpleLayout
  src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx
Labels: bug

#220 🚑️(frontend) fix MagnifyModal
  src/frontend/packages/core/src/components/design-system/Modal/index.test.tsx
  src/frontend/packages/core/src/components/design-system/Modal/index.tsx
Labels: bug

#225 ✨(frontend) Allow room administrator to show / hide input password
  src/frontend/packages/core/src/components/rooms/RoomConfig/RoomConfig.tsx
Labels: improvement

#226 ✨(frontend) Make the "Members" section always visible and functional
  src/frontend/packages/core/src/views/rooms/settings/index.test.tsx
  src/frontend/packages/core/src/views/rooms/settings/index.tsx
Labels: improvement

#227 ✨(frontend) fix make commands related to frontend
  Makefile
Labels: bug

#229 🌐(translations) fix translations issues in fr-FR.json
  CHANGELOG.md
  src/frontend/packages/core/i18n/compile-translations.cjs
  src/frontend/packages/core/i18n/locales/fr-FR.json
  src/frontend/packages/core/src/translations/fr-FR.json
  src/magnify/locale/fr/LC_MESSAGES/django.mo
Labels: improvement
